version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: practice4-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
    ports:
      - "3306:3306"
